# ===============================
# Server Configuration
# ===============================
server:
  port: 8083  # Order Service will run on port 8083

# ===============================
# Spring Application Configuration
# ===============================
spring:
  application:
    name: order-service  # Service name registered in Eureka

  # ===============================
  # Database Configuration (MySQL)
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db  # MySQL database URL
    username: root  # MySQL username
    password: 1234  # MySQL password

  # ===============================
  # JPA / Hibernate Configuration
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates DB schema based on entities
    show-sql: true      # Prints SQL queries in console (useful for debugging)

# ===============================
# Swagger / OpenAPI Configuration
# ===============================
springdoc:
  api-docs:
    path: /v3/api-docs  # Endpoint for OpenAPI JSON docs
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI access path

# ===============================
# Eureka Client Configuration
# ===============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL

# ===============================
# Resilience4j Configuration
# ===============================
resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true  # Expose circuit breaker health status in actuator
        slidingWindowSize: 10          # Number of calls used to calculate failure rate
        failureRateThreshold: 50       # % failures required to open the circuit breaker
        waitDurationInOpenState: 10s   # Time to stay OPEN before moving to HALF_OPEN

      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      userService:
        max-attempts: 3     # Total attempts (1 original + 2 retries)
        wait-duration: 1s   # Delay between retries

      productService:
        max-attempts: 3
        wait-duration: 1s

  timelimiter:
    instances:
      userService:
        timeout-duration: 2s  # Max time allowed before timing out

      productService:
        timeout-duration: 2s

# ===============================
# Actuator + Tracing Configuration
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh  # Exposes only health + info endpoints

  tracing:
    sampling:
      probability: 1.0  # Enables full tracing (useful for centralized logging + trace id)
